baseURL = 'https://keykey.kitchen/'
languageCode = 'id'
title = 'KeyKey Kitchen'
theme = 'ananke'
date_format = ':date_long'
defaultContentLanguage = 'id'
[languages]
[languages.id]
languageCode = 'id'
languageName = 'Bahasa Indonesia'
weight = 1
[languages.en]
languageCode = 'en'
languageName = 'English'
weight = 2
[params]
custom_css = ["search.css"]
background_color_class = "bg-dark-gray"
body_classes = "helvetica bg-washed-blue"
recent_posts_number = 20
